spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mantoi?autoReconnect=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: david_steam1233
  data:
    redis:
      host: 127.0.0.1
      port: 6379


jwt:
  secret: xyq0320
  expiration: 36000000