spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mantoi?autoReconnect=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: david_steam1233
  data:
    redis:
      host: 127.0.0.1
      port: 6379
    mongodb:
      uri: mongodb://localhost:27017/Mantoi
  cache:
    cache-names: cache
    caffeine:
      spec: initialCapacity=50,maximumSize=500,expireAfterWrite=10m
    type: caffeine


# mybatis-plus
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# Logging
logging:
  level:
    root: info

springdoc:
  swagger-ui:
    path: /swagger-ui.html